---
title: Introducing Molstar in Quarto
author: Jennifer HY Lin
date: '2024-3-27'
draft: true
categories: 
    - Notes
    - Visualisations
format:
  html:
    code-copy: true
toc: true
# molstar: embed
---

This is a short post for myself really and probably for others who may be interested in finding out alternative software tools for visualisaing macromolecules and small molecules in an *in silico* environment.

Most bioinformaticians or structural biologists are probably already very familiar with this package, which is known as Molstar (or also known as Mol^*). Molstar is a 3D viewer for large macromolecules such as proteins, which are commonly used for work in molecular biology, structural biology and drug discovery (and also other related scientific disciplines).

A Quarto extension is currently available that embeds a Molstar interactive 3D viewer inside a Quarto markdown document. The main advantage of this is that it could be useful for reporting or presentations in a multi-disciplinary setting, especially if the projects involved used protein structures (e.g. for a structure-based drug design project). The only thing to note is that this extension is for HTML pages only (since it's rendered from Quarto documents). 

Streamleit and Dash integrations examples are available.

Molstar webpage: https://molstar.org/

GitHub repository for the Quarto extension (thanks to the contributing team for this extension!): https://github.com/jmbuhr/quarto-molstar

Other Molstar example: https://ljmartin.github.io/sideprojects/dockviz2.html

R Shiny and Molstar example (for people who prefer using R): https://www.appsilon.com/post/shiny-molstar-r-package-molecular-structures-visualizations


### Example using RCSB PDB

Retrieve a protein from the RCSB PDB:

`{{{< mol-rcsb 4mqt >}}}`

{{< mol-rcsb 4mqt >}}


Click on the ligand to focus or zoom-in on the ligand bound to receptor protein. This shows most of the chemical interactions between the protein receptor and ligand bound to it (e.g. hydrogen bondings between the ligand and amino acid residues).

MD trajectories and screenshots available.

*Add citations of Molstar and others if relevant*